app/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^join/x/', views.join_x, name='join_x'),
    url(r'^join/o/', views.join_o, name='join_o'),
    url(r'^(?P<game_id>[0-9]+)/exit/x/', views.exit_x, name='exit_x'),
    url(r'^(?P<game_id>[0-9]+)/exit/o/', views.exit_o, name='exit_o'),
    url(r'^(?P<game_id>[0-9]+)/play/x', views.play_x, name='play_x'),
    url(r'^(?P<game_id>[0-9]+)/play/o', views.play_o, name='play_o'),
    url(r'^(?P<game_id>[0-9]+)/updateStatus/x', views.updateStatusX, name='updateStatusX'),
    url(r'^(?P<game_id>[0-9]+)/updateStatus/o', views.updateStatusO, name='updateStatusO'),
    url(r'^(?P<game_id>[0-9]+)/getStatus/x', views.getStatusX, name='getStatusX'),
    url(r'^(?P<game_id>[0-9]+)/getStatus/o', views.getStatusO, name='getStatusO'),
    url(r'^(?P<game_id>[0-9]+)/getPlayer/x', views.getPlayerX, name='getPlayerX'),
    url(r'^(?P<game_id>[0-9]+)/getPlayer/o', views.getPlayerO, name='getPlayerO'),
    url(r'^(?P<game_id>[0-9]+)/updateGameData', views.updateGameData, name='updateGameData'),
    url(r'^(?P<game_id>[0-9]+)/getNextPlayer', views.getNextPlayer, name='getNextPlayer'),
    url(r'^(?P<game_id>[0-9]+)/getTiles', views.getTiles, name='getTiles'),
    url(r'^(?P<game_id>[0-9]+)/getWinner', views.getWinner, name='getWinner'),
]    
    
    

project/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('app.urls')),
]

app/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.postgres.fields import ArrayField

@python_2_unicode_compatible
class Player(models.Model):
    alias = models.CharField(max_length=32)

    def __str__(self):
        return self.alias

@python_2_unicode_compatible
class Game(models.Model):
    tiles = ArrayField(
        models.CharField(max_length=1),
        default=[
            None, None, None,
            None, None, None,
            None, None, None
        ],
        size=9
    )
    status = models.CharField(max_length=32, null=True)
    nextPlayer = models.CharField( max_length=1, default='X')
    playerX = models.ForeignKey(Player, related_name="X", on_delete=models.CASCADE, null=True)
    playerO = models.ForeignKey(Player, related_name="O", on_delete=models.CASCADE, null=True)
    xState = models.CharField(max_length=16, default="not_ready")
    oState = models.CharField(max_length=16, default="not_ready")
    winner = models.CharField(max_length=1, null=True)

    def __str__(self):
        return '%s %s %s %s %s' % (
            self.tiles,
            self.state,
            self.playerNext,
            self.playerX,
            self.playerO
        )

app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
import json
from .models import Player
from .models import Game

def index(request):
     return render(request, "app/index.html")

def exit_x(request, game_id):
    game = Game.objects.get(id=game_id)
    game.playerX = None
    if game.playerO == None: 
        game.delete()
    else:
        game.status = 'waiting_for_players'
        game.save()

    return redirect ('app:index', permanent=True)

def exit_o(request, game_id):
    game = Game.objects.get(id=game_id)
    game.playerO = None

    if game.playerX == None:
        game.delete()
    else:
        game.status = 'waiting_for_players'
        game.save()

    return redirect ('app:index', permanent=True)

def join_x(request):
    # get alias from POST
    alias = request.POST['alias']
    
    # get if alias exists else create alias in Player model
    player, created = Player.objects.get_or_create(alias=alias)

    # check if empty playerX and waiting_for_players status exists
    # if found, join the first game_id in the list and change status to ready_to_play
    if Game.objects.filter(playerX=None, status="waiting_for_players").exists():
        game = Game.objects.filter(playerX=None, status="waiting_for_players").first()
        game.playerX = player
        game.status = 'ready_to_play'
        game.save()
    
    # if none found, create game with playerX assigned and set status to waiting_for_players
    else:
        game = Game.objects.create(status="waiting_for_players", playerX=player)
        game.save()

    return render(request, 'app/join.html', {
        'game': game,
        'xState': json.dumps(game.xState),
        'oState': json.dumps(game.oState),
    })

def join_o(request):
    # get alias from POST
    if 'alias' not in request.POST:
        alias = None
    else:
        alias = request.POST['alias']
        # get if alias exists else create alias in Player model
        player, created = Player.objects.get_or_create(alias=alias)
    
    
    
    # check if empty playerX and waiting_for_players status exists
    # if found, join the first game_id in the list and change status to ready_to_play
    if Game.objects.filter(playerO=None, status="waiting_for_players").exists():
        game = Game.objects.filter(playerO=None, status="waiting_for_players").first()
        game.playerO = player
        game.status = 'ready_to_play'
        game.save()

    # if none found, create game with playerX assigned and set status to waiting_for_players
    else:
        game = Game.objects.create(status="waiting_for_players", playerO=player)
        game.save()

    return render(request, 'app/join.html', {
        'game': game,
        'xState': json.dumps(game.xState),
        'oState': json.dumps(game.oState),
    })

def play_x(request, game_id):
    game = Game.objects.get(id=game_id)
    game.status = "game_in_progress"
    game.save()
    return render(request, 'app/game.html', {
        'game': game,
        'game_id': json.dumps(game.id),
        'game_nextPlayer': json.dumps(game.nextPlayer),
    })

def play_o(request, game_id):
    game = Game.objects.get(id=game_id)
    return render(request, 'app/game.html', {
        'game': game,
        'game_id': json.dumps(game.id),
        'game_nextPlayer': json.dumps(game.nextPlayer),
    })

def updateGameData(request, game_id):
    game = Game.objects.get(id=game_id)
    currentPlayer = game.nextPlayer

    position = request.POST['tilePosition']
    position = int(position)
    game.tiles[position] = currentPlayer

    winningPlays = [[0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8],
                    [0, 3, 6],
                    [1, 4, 7],
                    [2, 5, 8],
                    [0, 4, 8],
                    [2, 4, 6]]

    if (any(j is None for j in game.tiles)):
        game.nextPlayer = request.POST['nextPlayer']
    else:
        game.winner = 'T'
        game.status = 'finished'

    for i in winningPlays:
        #check if winning play exist
        if (game.tiles[i[0]] == currentPlayer and
            game.tiles[i[1]] == currentPlayer and
            game.tiles[i[2]] == currentPlayer):
            game.winner = currentPlayer
            game.status = 'finished'

    game.save()
    return HttpResponse(status=200)

## TODO: consolidate these functions
def getNextPlayer(request, game_id):
    game = Game.objects.get(id=game_id)
    return HttpResponse(json.dumps(game.nextPlayer))

def getTiles(request, game_id):
    game = Game.objects.get(id=game_id)
    return HttpResponse(json.dumps(game.tiles))

def getWinner(request, game_id):
    game = Game.objects.get(id=game_id)
    return HttpResponse(json.dumps(game.winner))

def updateStatusX(request, game_id):
    game = Game.objects.get(id=game_id) 
    game.xState = request.POST['xState']
    game.save()
    return HttpResponse(status=200)

def updateStatusO(request, game_id):
    game = Game.objects.get(id=game_id) 
    game.oState = request.POST['oState']
    game.save()
    return HttpResponse(status=200) 

def getStatusX(request, game_id):
    game = Game.objects.get(id=game_id) 
    return HttpResponse(json.dumps(game.xState))

def getStatusO(request, game_id):
    game = Game.objects.get(id=game_id) 
    return HttpResponse(json.dumps(game.oState))

def getPlayerX(request, game_id):
    game = Game.objects.get(id=game_id) 
    return HttpResponse(game.playerX)

def getPlayerO(request, game_id):
    game = Game.objects.get(id=game_id) 
    return HttpResponse(game.playerO)

templates/app/game.html
{% extends "base.html" %} {% block gamecontent %} {% load staticfiles %}
<script type="text/javascript">
    const game_id = JSON.parse("{{ game_id|escapejs }}");
      var game_nextPlayer = JSON.parse("{{ game_nextPlayer|escapejs }}");
    const url_updateGameData = "{% url 'app:updateGameData' game.id %}";
    const url_getNextPlayer = "{% url 'app:getNextPlayer' game.id %}";
    const url_getTiles = "{% url 'app:getTiles' game.id %}";
    const url_getWinner = "{% url 'app:getWinner' game.id %}"; 
</script>

<div class="game_title">
    <h2><strong>Tic Tac Toe</strong><small> {{ game.playerX }} vs {{ game.playerO }}</small></h2>
    <h5 class="player_status"></h5>
</div>
<div class="game_container">
    <div class="game_content">
        <div id="board">
            <div class="boardrow">
                <div class="tile" id="tile0" value='0'></div>
                <div class="tile" id="tile1" value='1'></div>
                <div class="tile" id="tile2" value='2'></div>
            </div>
            <div class="boardrow">
                <div class="tile" id="tile3" value='3'></div>
                <div class="tile" id="tile4" value='4'></div>
                <div class="tile" id="tile5" value='5'></div>
            </div>
            <div class="boardrow">
                <div class="tile" id="tile6" value='6'></div>
                <div class="tile" id="tile7" value='7'></div>
                <div class="tile" id="tile8" value='8'></div>
            </div>
        </div>
    </div>
</div>

<div id="newGamePrompt" class="modalPrompt">
  <div class="modalPrompt-content">
    <div>Game Over</div>
    <form action="{% url 'app:index' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="button button-primary btnPrompt">Play Again</div>
    </form>
  </div>
</div>

{% endblock gamecontent %} {% block afterbody %}
<script type="text/javascript" src='{% static "js/jquery-1.12.1.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/game.js" %}'></script>
<script type="text/javascript" src='{% static "js/getCookie.js" %}'></script>
{% endblock afterbody %}

templates/app/index.html
{% extends "base.html" %} {% block gamecontent %} {% load staticfiles %}
<div class="game_title">
  <h2><strong>Tic Tac Toe</strong></h2>
</div>

<div class="lobby_container">
  <div class="lobby_column">
    <div class="lobby_item" id="btnX">
      <div class="lobby_symbol">
        <i class="fa fa-times" aria-hidden="true"></i>
      </div>
    </div>
    <div id="formX">
      <form action="{% url 'app:join_x' %}" method="POST">
        {% csrf_token %}
        <input id="inputX" type="text" name="alias" placeholder="Flying Potato" required />
        <button type=submit class="button button-primary">Play</button>
      </form>
    </div>
  </div>
  <div class="lobby_column">
    <div class="lobby_item" id="btnO">
      <div class="lobby_symbol">
        <i class="fa fa-circle-o" aria-hidden="true"></i>
      </div>
    </div>
    <div id="formO">
      <form action="{% url 'app:join_o' %}" method="POST">
        {% csrf_token %}
        <input id="inputO" type="text" name="alias" placeholder="Noob Nooberton" required />
        <button type=submit class="button button-primary">Play</button>
      </form>
    </div>
  </div>
</div>

{% endblock gamecontent %} {% block afterbody %}
<script type="text/javascript" src='{% static "js/jquery-1.12.1.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/index.js" %}'></script>
{% endblock afterbody %}

templates/app/join.html
{% extends "base.html" %} {% block gamecontent %} {% load staticfiles %}

<script type="text/javascript">
  var lobby = {
    xState: JSON.parse('{{ xState|escapejs }}'),
    oState: JSON.parse('{{ oState|escapejs }}'),
    playerX: null,
    playerO: null
  }

  const getPlayerX = "{% url 'app:getPlayerX' game.id %}";
  const getPlayerO = "{% url 'app:getPlayerO' game.id %}";
  const updateStatusX = "{% url 'app:updateStatusX' game.id %}";
  const updateStatusO = "{% url 'app:updateStatusO' game.id %}";
  const getStatusX = "{% url 'app:getStatusX' game.id %}";
  const getStatusO = "{% url 'app:getStatusO' game.id %}";
  const play_x = "{% url 'app:play_x' game.id %}";
  const play_o = "{% url 'app:play_o' game.id %}";
  const exit_x = "{% url 'app:exit_x' game.id %}"
  const exit_o = "{% url 'app:exit_o' game.id %}"
  const index = "{% url 'app:index' %}"

</script>

<div class="game_title">
  <h2><strong>Tic Tac Toe</strong></h2>
</div>

<div class="lobby_container">
  {% url 'app:join_x' as x %} {% url 'app:join_o' as o %}
  <div class="lobby_column">
    <div class="lobby_item">
      <div class="lobby_symbol">
        <i class="fa fa-times" aria-hidden="true"></i>
      </div>
    </div>

    <div class="lobby_item">
      {% if request.path == x %} {{ game.playerX }} {% elif request.path == o %}
      <div id="lobby_playerX">
        {% if not game.playerX %} Waiting for player... {% endif %}
      </div>
      {% endif %}
    </div>

    <div class="lobby_item">
      {% if request.path == x %}
      <label class="switch">
          <input class="checkbox" type="checkbox">
          <div class="slider round"></div>
        </label> {% elif request.path == o %}
      <div id="lobby_xState"></div>
      {% endif %}
    </div>

    {% if request.path == x %}
    <div class="lobby_item">
      <form id="formExitX" action="{% url 'app:exit_x' game.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">go back</button>
      </form>
    </div>
    {% endif %}
  </div>

  <div class="lobby_column">
    <div class="lobby_item">
      <div class="lobby_symbol">
        <i class="fa fa-circle-o" aria-hidden="true"></i>
      </div>
    </div>

    <div class="lobby_item">
      {% if request.path == x %}
      <div id="lobby_playerO">
        {% if not game.playerO %} Waiting for player... {% endif %}
      </div>
      {% elif request.path == o %} {{ game.playerO }} {% endif %}
    </div>

    <div class="lobby_item">
      {% if request.path == x %}
      <div id="lobby_oState"></div>
      {% elif request.path == o %}
      <label class="switch">
          <input class="checkbox" type="checkbox">
          <div class="slider round"></div>
        </label> {% endif %}
    </div>

    {% if request.path == o %}
    <div class="lobby_item">
      <form id="formExitO" action="{% url 'app:exit_o' game.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">go back</button>
      </form>
    </div>
    {% endif %}

  </div>
</div>

<div id="myModal" class="modal">
  <div class="modal-content">
    <div class="modal-top">Starting game...</div>
    <div class="loader"></div>
  </div>
</div>

{% endblock gamecontent %} {% block afterbody %}
<script type="text/javascript" src='{% static "js/jquery-1.12.1.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/getCookie.js" %}'></script>
<script type="text/javascript" src='{% static "js/join.js" %}'></script>
{% endblock afterbody %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Tic Tac Toe{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600,200' rel='stylesheet' type='text/css'>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="section">
    <div class="container">
      {% block content %}{% endblock content %}
      {% block gamecontent %}{% endblock gamecontent %}
    </div>
  </div>  
  {% block afterbody %}{% endblock afterbody %}
</body>
</html>